### ISSUE TITLE
Replace Header Search Bar with Input Group

### ISSUE THREAD

**Issue by shreyansqt** [jatinsayan/education-dashboard#1]
https://github.com/jatinsayan/education-dashboard/blob/ad93e5746f45e9a45f686b4176c2c30cb8bee571/index.html#L66-L69

Try using input group here
https://getbootstrap.com/docs/4.0/components/input-group/#button-addons

**Comment by jatinsayan** [comment]
Issue fixed! ( id : cc7876d0f6c8e5f7a5a0276de9b5aa1864c06302 )

**Comment by shreyansqt** [comment]
We should update the design of the input, and / or input-group to match the design as well
