### ISSUE TITLE
Add Icons to Sidenav Links

### ISSUE THREAD

**Issue by shreyansqt** [jatinsayan/education-dashboard#2]
https://github.com/jatinsayan/education-dashboard/blob/9375cfe62903c91deccabc1b038abe7275ef21fe/index.html#L34-L50

Please add icons to these links as per the design.

**Comment by jatinsayan** [comment]
Fixed ( id : 4770576196861f0cf620f8b4c9d472732fe3b33a )

**Comment by shreyansqt** [comment]
SideNav looks great!
