### ISSUE TITLE
Fix the nav-tabs styles

### ISSUE THREAD

**Issue by shreyansqt** [jatinsayan/education-dashboard#4]
The text styles for nav tabs look pretty good. I think hover / active styles and spacing needs 
improvement. 

Code - 
<img width="831" alt="screen shot 2017-12-22 at 3 53 47 pm" src="https://user-images.githubusercontent.com/7807851/34294854-740047de-e730-11e7-92d9-dfcd70817d92.png">

Design - 
<img width="746" alt="screen shot 2017-12-22 at 3 53 15 pm" src="https://user-images.githubusercontent.com/7807851/34294841-6594d142-e730-11e7-97ee-2678d472b97a.png">

**Comment by jatinsayan** [comment]
Fixed ( Id : f4072b943455b5e04b1a2b3daba9cf06afd3d3d2 )
